fix test code for 23-erc865-and-erc875
rebase-network/Dapp-Learning pull request #112
Opened 2021-08-03 11:33 UTC by yingjingyang

2021-08-04 01:08 UTC, liberhe submitted a review, later dismissed

2021-08-04 02:53 UTC, luckyyang requested changes
有几个地方需要改一下

2021-08-04 02:53 UTC, luckyyang commented on basic/23-erc865-and-erc875/hardhat.config.js
> + return process.env.PRIVATE_KEY;
应该有两个空格？

2021-08-04 02:53 UTC, luckyyang commented on basic/23-erc865-and-erc875/hardhat.config.js
> +      url: "https://rinkeby.infura.io/v3/0aae8358bfe04803b8e75bb4755eaf07", //<---- YOUR INFURA ID! (or it won't work)
infura id 其实也可以放到 ENV 中

2021-08-04 02:53 UTC, luckyyang commented on basic/23-erc865-and-erc875/test/test_DToken.js
> +      // Sign the message_bytes by alice
by Bob

2021-08-04 02:53 UTC, luckyyang commented on basic/23-erc865-and-erc875/test/test_DToken.js
> +      let dTokenAlice = dTokenOwner.connect(alice);
如果某个变量没有被重新赋值，最好用 const

2021-08-04 02:54 UTC, luckyyang commented
另外我看 ERC875.sol 这个合约的格式比较乱，最好能格式化一下

2021-08-04 04:05 UTC, yingjingyang commented on basic/23-erc865-and-erc875/hardhat.config.js
> + return process.env.PRIVATE_KEY;
已修改

2021-08-04 04:06 UTC, yingjingyang commented on basic/23-erc865-and-erc875/hardhat.config.js
> +      url: "https://rinkeby.infura.io/v3/0aae8358bfe04803b8e75bb4755eaf07", //<---- YOUR INFURA ID! (or it won't work)
已修改

2021-08-04 04:06 UTC, yingjingyang commented on basic/23-erc865-and-erc875/test/test_DToken.js
> +      // Sign the message_bytes by alice
已修改

2021-08-04 04:06 UTC, yingjingyang commented on basic/23-erc865-and-erc875/test/test_DToken.js
> +      let dTokenAlice = dTokenOwner.connect(alice);
已修改

2021-08-04 15:26 UTC, liberhe approved these changes

2021-08-05 01:31 UTC, luckyyang approved these changes

2021-08-05 01:32 UTC, merged