daohaus分析追加
rebase-network/Dapp-Learning pull request #117
Opened 2021-08-05 07:32 UTC by jhfnetboy

添加了三个文档
1.launch文档，翻译自Medium官方，做了一些校对，close
2.code文档，新增，做了一点分析，后面是对目录结构内的代码分析工作，准备一周做一些提交，doing
3.contract，daohaus调用的moloch v2的智能合约，对此也做一些分析，先占位，todo

2021-08-05 07:37 UTC, yingjingyang submitted a review, later dismissed

2021-08-05 13:46 UTC, liberhe approved these changes

2021-08-06 00:51 UTC, maroonstar requested changes

2021-08-06 00:51 UTC, maroonstar commented on dao/DAOhaus/Dauhaus-Code.md
> ++ 欢迎认领~！联系 Survivor
可以换成issue链接 
[点这里留言报名 👉](https://github.com/rebase-network/Dapp-Learning/issues/99)

2021-08-06 00:56 UTC, maroonstar submitted a review, later dismissed

2021-08-06 01:27 UTC, liberhe approved these changes

2021-08-06 02:04 UTC, maroonstar approved these changes

2021-08-06 02:24 UTC, liberhe approved these changes

2021-08-06 02:24 UTC, merged