AAVE whitepaper share - part
rebase-network/Dapp-Learning pull request #255
Opened 2021-09-20 05:50 UTC by bixia

According to the discussion with the rebase team member, it is recommend to commit fast and discuss fast. so, i just post my current status to it, and update it later.

2021-09-20 07:37 UTC, maroonstar requested changes

2021-09-20 07:37 UTC, maroonstar commented on defi/Aave/AAVE whitepaper V1.md
> +$$
You might need a hack for showing LaTeX formulas in GitHub markdown.md. See usage in this: https://gist.github.com/a-rodin/fef3f543412d6e1ec5b6cf55bf197d7b

2021-09-23 09:50 UTC, jhfnetboy approved these changes

2021-09-23 10:16 UTC, jhfnetboy approved these changes

2021-09-25 03:15 UTC, maroonstar approved these changes

2021-09-25 03:16 UTC, merged