Add new 56.[Liquity] task and correct the missing 55.[PBFT] task in R…
rebase-network/Dapp-Learning pull request #265
Opened 2021-09-21 11:08 UTC by zhengger

…EADME-en.md

2021-09-21 14:37 UTC, yingjingyang approved these changes

2021-09-21 15:16 UTC, liberhe requested changes
why you change so many lines. Please use the prettier to formate your code

2021-09-21 15:56 UTC, zhengger commented
> why you change so many lines. Please use the prettier to formate your code

Sorry, I may reformat the file accidentally. There are only 3 lines changed indeed. I'll PR agian.

2021-09-23 06:24 UTC, jhfnetboy requested changes
close and resend again.
be sure to check your local changes

2021-09-23 10:16 UTC, jhfnetboy submitted a review, later dismissed

2021-09-23 10:20 UTC, yingjingyang approved these changes

2021-09-23 10:22 UTC, closed without merging