1 更新hardhat 到最新稳定版本 2.6.4 并在本地验证通过
rebase-network/Dapp-Learning pull request #289
Opened 2021-09-27 09:16 UTC by yux829

2 更新README文档步骤说明

2021-09-27 09:52 UTC, liberhe submitted a review, later dismissed

2021-09-27 10:03 UTC, liushooter requested changes

2021-09-27 12:15 UTC, liberhe approved these changes

2021-09-27 12:35 UTC, maroonstar requested changes

2021-09-27 12:35 UTC, maroonstar commented on basic/07-hardhat/README.md
> +```cnpm install
this may write a new line, and please use npm or yarn, not cnpm

2021-09-27 12:56 UTC, maroonstar approved these changes

2021-09-27 12:58 UTC, maroonstar approved these changes

2021-09-28 03:26 UTC, liberhe approved these changes

2021-09-28 03:38 UTC, liushooter approved these changes

2021-09-28 03:38 UTC, merged