Create nft与数字身份随想.md
rebase-network/Dapp-Learning pull request #310
Opened 2021-10-01 01:52 UTC by nigdaemon

xiakezhang PR

2021-10-01 02:06 UTC, bobjiang approved these changes
Like this idea

2021-10-01 09:34 UTC, jhfnetboy submitted a review, later dismissed
Great~
It seems you should hold a talk in community, for this topic, exchange our ideas~

2021-10-02 10:32 UTC, maroonstar requested changes
That's a great idea! But this is not a task or  a course, put it in isses would be better I think. 😄

2021-10-03 01:45 UTC, liberhe commented on nft/nft与数字身份随想.md
> +信用借贷由于无抵押，所以要根据所有的历时行为计算借款人的偿付能力。同时，为了做最后一道保障，也就是借款人跑路的情况下，如何去追偿。
"历时行为"

2021-10-03 01:49 UTC, liberhe commented on nft/nft与数字身份随想.md
> +这些是我一个初步的产品设计思考，有感兴趣的小伙伴可以联系我，大家一起探讨，没准可以做成一个项目。或者有技术实力的团队也可以去尝试下是否可行~
what you want to do is to implant Web3 identity? Is it safe to say so?

2021-10-03 01:52 UTC, maroonstar approved these changes

2021-10-03 02:30 UTC, maroonstar approved these changes

2021-10-03 14:17 UTC, liberhe approved these changes

2021-10-03 14:18 UTC, maroonstar approved these changes

2021-10-03 14:19 UTC, merged