sdk v2 describe complete
rebase-network/Dapp-Learning pull request #312
Opened 2021-10-02 08:34 UTC by jhfnetboy

sdk v2 readme and basic describe complete

2021-10-02 10:16 UTC, maroonstar requested changes
Lots of lines need a minus or `<br>`, please modify.

2021-10-02 10:16 UTC, maroonstar commented on defi/Uniswap-V2/SDK/readme.md
> +1.prevent installation of unused dependencies (e.g. @ethersproject/providers and @ethersproject/contracts, only used in Fetcher)
need a space after dot like this:

1. xxxx
2. xxx

2021-10-02 10:16 UTC, maroonstar commented on defi/Uniswap-V2/SDK/readme.md
> +liquidityToken
need  a minus before each line:

- liquidityToken
-  xxx

2021-10-02 10:16 UTC, maroonstar commented on defi/Uniswap-V2/SDK/readme.md
> +tradeType
need a minus too.

2021-10-02 10:16 UTC, maroonstar commented on defi/Uniswap-V2/SDK/readme.md
> +返回最大值可能
最优交易路径（手续费最低）

2021-10-02 11:23 UTC, jhfnetboy commented on defi/Uniswap-V2/SDK/readme.md
> +返回最大值可能
this method returns the best maxNumResults trades that swap an input token amount to an output token
看起来这句话是返回的是一个最大值兑换可能啊。。。最优路径我理解是返回合适的交易对路径，很明显这个函数不是返回交易对的

2021-10-02 11:34 UTC, maroonstar commented on defi/Uniswap-V2/SDK/readme.md
> +返回最大值可能
返回的是 Trade 类型 的数组，Trade类型是两个token组成的交易，返回值就是依照这个交易对序列顺序执行交易，中间的损耗最小（手续费和gas），所以获得的输出数量也是最多的 （best maxNumResults）

2021-10-02 11:37 UTC, maroonstar commented on defi/Uniswap-V2/SDK/readme.md
> +返回最大值可能
可以参考interface对这种方法的应用过程 https://github.com/rebase-network/Dapp-Learning/blob/main/defi/Uniswap-V2/Interface/Code.md#usetradeexactout

2021-10-03 08:12 UTC, jhfnetboy commented on defi/Uniswap-V2/SDK/readme.md
> +返回最大值可能
get~

2021-10-03 14:41 UTC, maroonstar approved these changes

2021-10-04 04:55 UTC, liberhe approved these changes

2021-10-05 02:45 UTC, merged