Update README.md
rebase-network/Dapp-Learning pull request #317
Opened 2021-10-05 15:48 UTC by xrdavies

Add contributors' avatars in README

2021-10-06 00:36 UTC, bobjiang requested changes
move to bottom in README.

2021-10-06 05:04 UTC, xrdavies commented
> move to bottom in README.

Done

2021-10-06 06:59 UTC, liberhe approved these changes

2021-10-07 02:33 UTC, luckyyang approved these changes

2021-10-07 04:13 UTC, merged