add web3.0 dapp task
rebase-network/Dapp-Learning pull request #421
Opened 2021-11-05 15:06 UTC by fewwwww

2021-11-06 05:48 UTC, luckyyang requested changes
需要调整有些内容

2021-11-06 05:48 UTC, luckyyang commented on basic/59-web3-dapp/1. eth.build 快速上手 | Web3.0 dApp 开发.md
> +从微信下载个人二维码后，通过草料二维码（https://cli.im/deqr）将二维码转换为`URL`，输入`Text`中即可。
这个链接会和后面的文字连起来，建议加个空格

2021-11-06 05:48 UTC, luckyyang commented on basic/59-web3-dapp/2. scaffold-eth 快速上手 | web3.0 dApp开发.md
> +- **hardhat：**用于运行本地网络、部署和测试智能合约。
** 后面应该加个空格，要不然解析不出来

2021-11-06 05:48 UTC, luckyyang commented on basic/59-web3-dapp/2. scaffold-eth 快速上手 | web3.0 dApp开发.md
> +## 关于作者
这里不建议放个人信息

2021-11-06 05:48 UTC, luckyyang commented on basic/59-web3-dapp/3. 值的存取应用1.0 | web3.0 dApp开发.md
> +![image-20211002001028548](/Users/liaohua/Documents/008i3skNly1gv09gs9t3mj60d603i3yd02.png)
这个文档的图片无法显示

2021-11-06 05:48 UTC, luckyyang commented on basic/59-web3-dapp/4. 值的存取应用2.0 |  Web3.0 dApp 开发.md
> +> // TODO
todo 是什么意思

2021-11-06 05:48 UTC, luckyyang commented on basic/59-web3-dapp/4. 值的存取应用2.0 |  Web3.0 dApp 开发.md
> +![image-20211029132355937](/Users/liaohua/Documents/image-20211029132355937.png)
图片无法显示

2021-11-06 05:48 UTC, luckyyang commented on basic/59-web3-dapp/4. 值的存取应用2.0 |  Web3.0 dApp 开发.md
> +## 0x03 Web3.0 dApp Dev 训练营
这句可以删掉？

2021-11-07 00:22 UTC, jhfnetboy reviewed
how about the true modifys? just formate the line and remove blanks?

2021-11-10 15:07 UTC, luckyyang approved these changes

2021-11-11 01:57 UTC, liberhe submitted a review, later dismissed

2021-11-11 03:35 UTC, maroonstar submitted a review, later dismissed

2021-11-11 03:42 UTC, maroonstar approved these changes

2021-11-11 15:48 UTC, yingjingyang approved these changes

2021-11-11 15:48 UTC, merged